### ISSUE TITLE
Verify connection returns error body with HTTP 200

### ISSUE THREAD

**Issue by jludvice** [syndesisio/syndesis-verifier#36]
![http_200_error](https://user-images.githubusercontent.com/8707241/30798011-4263c662-a1d8-11e7-9156-3e933856d3ec.png)

Request url: https://syndesis-qe.b6ff.rh-idev.openshiftapps.com/api/v1/connectors/twitter/verifier
response body:
```json
[
    {
        "status": "UNSUPPORTED",
        "scope": "PARAMETERS",
        "errors": [
            {
                "code": "internal-error",
                "description": "No action twitter-mention used for the verification known",
                "parameters": [],
                "attributes": {}
            }
        ]
    }
]
```

How is it possible that status code is set to 200 / OK for verification error @rhuss @zregvart

**Comment by zregvart** [comment]
The contract of the verifier is that it provides the verification result, if it's successful in providing a verification result even though that verification result contains an erroneous response. I think it makes sense to return OK status if it is not the verifier that has failed.
