### ISSUE TITLE
Use Salesforce field labels for displayValue

### ISSUE THREAD

**Issue by zregvart** [syndesisio/syndesis-verifier#45]
Metadata adapter/extension for Salesforce seems to return field name instead of field label for displayValue in PropertyPair. This leads to custom fields being displayed to the end users with their `__c` suffix.

**Comment by zregvart** [comment]
This should extend to all metadata, including Salesforce data shapes

**Comment by rhuss** [comment]
Please ping docs, too, when changing as this affects the tutorials.
